// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8L-0L8AzMyXM35Sf-vnM2BNAFf7qpC5c',
    appId: '1:163390486216:web:9713dfac77e20b2d75d7fd',
    messagingSenderId: '163390486216',
    projectId: 'flutter-project-2102a',
    authDomain: 'flutter-project-2102a.firebaseapp.com',
    databaseURL: 'https://flutter-project-2102a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-2102a.firebasestorage.app',
    measurementId: 'G-LM0GL5Q5HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcXwvcjGqTGrfESYqJAJc0JxgfHPWWiug',
    appId: '1:163390486216:android:2b778bfb35b6137475d7fd',
    messagingSenderId: '163390486216',
    projectId: 'flutter-project-2102a',
    databaseURL: 'https://flutter-project-2102a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-2102a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzwe-CMSPxx4j0dw2ss2zaRhzfdPKo6A',
    appId: '1:163390486216:ios:e139345e62835dba75d7fd',
    messagingSenderId: '163390486216',
    projectId: 'flutter-project-2102a',
    databaseURL: 'https://flutter-project-2102a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-2102a.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzwe-CMSPxx4j0dw2ss2zaRhzfdPKo6A',
    appId: '1:163390486216:ios:e139345e62835dba75d7fd',
    messagingSenderId: '163390486216',
    projectId: 'flutter-project-2102a',
    databaseURL: 'https://flutter-project-2102a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-2102a.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8L-0L8AzMyXM35Sf-vnM2BNAFf7qpC5c',
    appId: '1:163390486216:web:9713dfac77e20b2d75d7fd',
    messagingSenderId: '163390486216',
    projectId: 'flutter-project-2102a',
    authDomain: 'flutter-project-2102a.firebaseapp.com',
    databaseURL: 'https://flutter-project-2102a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-2102a.firebasestorage.app',
    measurementId: 'G-LM0GL5Q5HE',
  );

}